version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:1.13.3
    container_name: consul-server
    restart: always
    volumes:
      - ./server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.13.3
    # container_name: consul-client
    restart: always
    volumes:
      - ./client.json:/consul/config/client.json:ro
    networks:
      - consul
    command: "agent"

  consul-terraform-sync:
    image: hashicorp/consul-terraform-sync:latest
    container_name: consul-terraform-sync
    restart: always
    volumes:
      - ./cts.hcl:/config/cts.hcl
    environment:
      - PANOS_HOSTNAME=${PANOS_HOSTNAME}
      - PANOS_USERNAME=${PANOS_USERNAME}
      - PANOS_API_KEY=${PANOS_API_KEY}
      - CONSUL_HTTP_ADDR=consul-server:8500
    networks:
      - consul
    command: "consul-terraform-sync -config-file=/config/cts.hcl"

networks:
  consul:
    driver: bridge
